notifications:
  slack:
    rooms:
      secure: nSUPxSqmTkHwieKUM3NdVq3/2A1QpKZj58c3hQIWYtYo0TSgNB9YFKp90ZyLKf2njaU4iC/TDojtiHt91UKdsPDwXNCvE1Lokl753MzzbnEDpAOYTy4y9PZYnzAHsKu17Y1ZS0q6p9LCL3ob+rmaVs59cWp11Dv+Ex/mjKxfMikKUejLH8hiZ6suwahoBm7BgeVTIJX+RoEsvtsu6LXw+WTGxdziulo0jUYcwVubyYiSkjMVCLW/ugzibdQVUoK3N3IK1DCu4uwaQKR3kHcdRV96ZLIJdIsbUncdVtjS1fDVNbI1XzhiAqiiUUHGojtdJc+iF1VEVfEf7XXOW8muVB9G9NOINS8Zw3vgfcYHGh9ionUnL0ZTxPK8LGdvJe5m8u8fPpvQ90tYzgt8CrP5AIEtjUFEc0hE8OG/YjNB8RpgjpoSrL0ms66ylMYC7u9DlJ3wAxawaqCycNs9+NmcCh8OYfsNfWMqnZvks5FtlSry/cdWxCLN5YRscHH7nKHNHsARolCTRkwKm6EJ2oN+unhGo5n7BKpe+DxzDNF3IO2+jJSrmLnj5zvTHUlCGf/sDo1sC/TByW/aT/XDLU0UskhWIj1X/Q8FqX+BGbuxlZ2ZCKXntYWrYzBa+d8cXUrSON19ahHQtxGmBY2oNrziMzoKy1xC5g8S9CivMUPI5bc=

env:
  - DOCKER_COMPOSE_VERSION=1.24.1

language: python
python: "3.7"

before_install:
  - sudo make configure
  - sudo apt-get update
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker ps

install:
  - npm install newman
  - sudo apt install -y curl apache2-utils

before_script:
  - make compose

after_script:
  - make decompose

jobs:
  include:
    - stage: test
      name: "Newman"
      language: node_js
      node_js: 13.2.0
      script: make travis-nm
    - name: "Curl"
      script: make curl
    - name: "Apache Benchmark"
      script: make ab

deploy:
  provider: elasticbeanstalk
  region: 'eu-north-1'
  app: 'apy'
  env: 'Apy-env'
  bucket_name: 'elasticbeanstalk-eu-north-1-719789094322'
  bucket_path: 'apy'
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY

stages:
  - test
  - deploy