notifications:
  slack:
    rooms:
      secure: nSUPxSqmTkHwieKUM3NdVq3/2A1QpKZj58c3hQIWYtYo0TSgNB9YFKp90ZyLKf2njaU4iC/TDojtiHt91UKdsPDwXNCvE1Lokl753MzzbnEDpAOYTy4y9PZYnzAHsKu17Y1ZS0q6p9LCL3ob+rmaVs59cWp11Dv+Ex/mjKxfMikKUejLH8hiZ6suwahoBm7BgeVTIJX+RoEsvtsu6LXw+WTGxdziulo0jUYcwVubyYiSkjMVCLW/ugzibdQVUoK3N3IK1DCu4uwaQKR3kHcdRV96ZLIJdIsbUncdVtjS1fDVNbI1XzhiAqiiUUHGojtdJc+iF1VEVfEf7XXOW8muVB9G9NOINS8Zw3vgfcYHGh9ionUnL0ZTxPK8LGdvJe5m8u8fPpvQ90tYzgt8CrP5AIEtjUFEc0hE8OG/YjNB8RpgjpoSrL0ms66ylMYC7u9DlJ3wAxawaqCycNs9+NmcCh8OYfsNfWMqnZvks5FtlSry/cdWxCLN5YRscHH7nKHNHsARolCTRkwKm6EJ2oN+unhGo5n7BKpe+DxzDNF3IO2+jJSrmLnj5zvTHUlCGf/sDo1sC/TByW/aT/XDLU0UskhWIj1X/Q8FqX+BGbuxlZ2ZCKXntYWrYzBa+d8cXUrSON19ahHQtxGmBY2oNrziMzoKy1xC5g8S9CivMUPI5bc=

language: python

services:
  - docker

